agents:
  - id: casual talk
    role: casual talk
    goal: are you able to remember information from previuos yaml configs?

  - id: writer
    role: Technical Writer
    goal: Convert research into documentation

workflow:
  type: sequential
  steps:
    - agent: casual talk
    - agent: writer